From centos:centos7
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm && \
    cd /root && \
    yumdownloader zabbix-server-mysql && \
    rpm2cpio zabbix-server-mysql* | cpio -id ./usr/share/doc/zabbix-server-mysql-*/create.sql.gz && \
    mv ./usr/share/doc/zabbix-server-mysql-*/create.sql.gz . && \
    rm -rf zabbix-server-mysql* ./usr
RUN yum -y install mariadb-server
ADD my.cnf /etc/my.cnf
CMD /usr/libexec/mariadb-prepare-db-dir mariadb && /usr/bin/mysqld_safe --basedir=/usr
