From centos:centos7
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN rpm -ivh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm && \
    yum -y install zabbix-server-mysql mysql
ADD zabbix_server.conf /etc/zabbix/zabbix_server.conf
CMD ["/usr/sbin/zabbix_server", "-c", "/etc/zabbix/zabbix_server.conf", "-f"]